set(_source "${QXMPP_SOURCE_DIR}/src/omemo/OmemoCryptoProvider.cpp")
if(NOT EXISTS "${_source}")
    message(FATAL_ERROR "QXmpp OMEMO source not found: ${_source}")
endif()

file(READ "${_source}" _contents)
set(_old "mac->addData(QByteArrayView(reinterpret_cast<const char *>(data), data_len));")
set(_new "mac->addData(reinterpret_cast<const char *>(data), qsizetype(data_len));")

string(FIND "${_contents}" "${_old}" _old_position)
string(FIND "${_contents}" "${_new}" _new_position)

if(NOT _old_position EQUAL -1)
    string(REPLACE "${_old}" "${_new}" _contents "${_contents}")
    file(WRITE "${_source}" "${_contents}")
    message(STATUS "Patched QXmpp 1.15.1 for QMessageAuthenticationCode on Qt 6.4")
elseif(_new_position EQUAL -1)
    message(FATAL_ERROR "Unsupported QXmpp OmemoCryptoProvider.cpp; Qt 6.4 compatibility patch could not be applied")
else()
    message(STATUS "QXmpp Qt 6.4 compatibility patch is already applied")
endif()
