.TH QTNOTE 1 "July 12, 2013"
.SH NAME
qtnote \- Qt note-taking application
.SH SYNOPSIS
.B qtnote
.RI [ options ]
.SH DESCRIPTION
\fBqtnote\fP lives in your system tray area and allows you to make notes quickly
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-n [type]
Create new note. Optional `type` param means source of contents.
only `selection` type is currently supported and you have to install xsel util to use it.
.SH AUTHOR
qtnote was written by Sergei Ilinykh.
